const state={products:[],categories:[],guides:[],filter:'all',query:'',compare:[],saved:new Set(JSON.parse(localStorage.getItem('rp_saved')||'[]')),sessionId:(crypto.randomUUID?crypto.randomUUID():String(Date.now()))};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2200)}
function logEvent(name,metadata={}){try{const arr=JSON.parse(localStorage.getItem('rp_events')||'[]');arr.push({event_name:name,session_id:state.sessionId,metadata,occurred_at:new Date().toISOString()});localStorage.setItem('rp_events',JSON.stringify(arr.slice(-500)))}catch{}fetch('/api/event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event_name:name,session_id:state.sessionId,metadata})}).catch(()=>{})}
function renderCategories(){$('#categoryGrid').innerHTML=state.categories.map(c=>`<button class="cat" data-category="${esc(c[1])}"><div class="icon">${c[0]}</div><b>${esc(c[1])}</b></button>`).join('');$$('#categoryGrid .cat').forEach(b=>b.onclick=()=>setFilter(b.dataset.category))}
function matches(p,q){if(!q)return true;const hay=[p.name,p.brand,p.category,p.model,p.problem_solved,...(p.use_cases||[]),...(p.subcategories||[])].join(' ').toLowerCase();const terms=q.toLowerCase().split(/\s+/).filter(Boolean);const alias={rumah:'home',handuk:'towel',kamar:'bathroom',dapur:'kitchen',gadget:'electronics',bayi:'baby',alat:'tools',praktis:'smart'};return terms.every(t=>hay.includes(t)||(alias[t]&&hay.includes(alias[t])))}
function filtered(){return state.products.filter(p=>(state.filter==='all'||p.category===state.filter)&&matches(p,state.query))}
function card(p){return `<article class="card"><div class="visual"><span class="badge">${esc(p.editorial_status||'PICK')}</span><div class="mark">✓</div></div><div class="body"><div class="micro">${esc(p.brand)} · ${esc(p.category)}</div><h3>${esc(p.name)}</h3><p>${esc(p.problem_solved)}</p><div class="pills">${(p.claims||[]).slice(0,3).map(c=>`<span class="pill">${esc(c.text)}</span>`).join('')}</div><div class="actions"><button class="btn btn-dark" data-action="detail" data-id="${esc(p.product_id)}">Lihat Detail</button><button class="btn" data-action="compare" data-id="${esc(p.product_id)}">${state.compare.includes(p.product_id)?'✓ Compared':'+ Compare'}</button><button class="btn" data-action="save" data-id="${esc(p.product_id)}">${state.saved.has(p.product_id)?'★':'☆'}</button></div></div></article>`}
function renderProducts(){const list=filtered();if(!list.length){$('#productGrid').innerHTML='<div class="panel" style="grid-column:1/-1;text-align:center"><b>Belum ada kandidat yang cocok.</b><p class="muted">Zero-result search menjadi research signal untuk discovery berikutnya.</p></div>';return}$('#productGrid').innerHTML=list.map(card).join('');$$('#productGrid [data-action]').forEach(el=>el.onclick=()=>{const id=el.dataset.id;const a=el.dataset.action;a==='detail'&&openProduct(id);a==='compare'&&toggleCompare(id);a==='save'&&toggleSave(id)})}
function openProduct(id){const p=state.products.find(x=>x.product_id===id);if(!p)return;$('#modalBrand').textContent=`${p.brand} · ${p.category}`;$('#modalTitle').textContent=p.name;$('#modalProblem').textContent=p.problem_solved;$('#modalSignals').innerHTML=(p.claims||[]).map(c=>`<span class="pill">${esc(c.text)}</span>`).join('');$('#modalEvidence').innerHTML=`<strong>Evidence status:</strong> ${esc(p.status)}<br><br>${esc(p.notes)}<br><br><strong>Affiliate disclosure:</strong> Bila kamu membeli melalui route yang tersedia dan programnya aktif, RuangPilih dapat menerima komisi.`;$('#modalBuy').href=p.affiliate?.publisher_page||p.affiliate?.route||'#';$('#modalCompare').onclick=()=>{toggleCompare(id);closeModal('productOverlay')};$('#productOverlay').classList.remove('hidden');logEvent('product_view',{product_id:id})}
function closeModal(id){$('#'+id).classList.add('hidden')}
function toggleSave(id){state.saved.has(id)?state.saved.delete(id):state.saved.add(id);localStorage.setItem('rp_saved',JSON.stringify([...state.saved]));renderProducts();toast(state.saved.has(id)?'Disimpan ke RuangPilih':'Dihapus dari simpanan');logEvent('save_toggle',{product_id:id,saved:state.saved.has(id)})}
function toggleCompare(id){if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else{if(state.compare.length>=4)return toast('Maksimal 4 produk.');state.compare.push(id)}renderProducts();updateCompare();logEvent('compare_toggle',{product_id:id,selected:state.compare.includes(id)})}
function updateCompare(){$('#compareCount').textContent=state.compare.length;$('#compareBar').classList.toggle('show',state.compare.length>0)}
function openCompare(){const ps=state.compare.map(id=>state.products.find(p=>p.product_id===id)).filter(Boolean);$('#compareContent').innerHTML=ps.length?`<table class="compare-table"><thead><tr><th>Dimension</th>${ps.map(p=>`<th>${esc(p.name)}</th>`).join('')}</tr></thead><tbody><tr><td>Brand</td>${ps.map(p=>`<td>${esc(p.brand)}</td>`).join('')}</tr><tr><td>Use cases</td>${ps.map(p=>`<td>${esc((p.use_cases||[]).join(', '))}</td>`).join('')}</tr><tr><td>Evidence</td>${ps.map(p=>`<td>${esc(p.status)}</td>`).join('')}</tr><tr><td>Affiliate</td>${ps.map(p=>`<td>${p.affiliate?.status==='VERIFIED_ACTIVE'?'Available':'Pending verification'}</td>`).join('')}</tr></tbody></table><p class="muted" style="font-size:10px">Recommendation economics never override product fit.</p>`:'<div class="panel">Belum ada produk dipilih.</div>';$('#compareOverlay').classList.remove('hidden');logEvent('compare_open',{ids:state.compare})}
function setFilter(f){state.filter=f;$$('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderProducts();location.hash='picks'}
function runSearch(){state.query=$('#heroSearch').value.trim()||$('#navSearch').value.trim();renderProducts();$('#picks').scrollIntoView({behavior:'smooth'});logEvent('search',{query:state.query})}
async function aiRecommend(){const q=$('#aiInput').value.trim();if(!q)return toast('Ceritakan kebutuhanmu dulu.');$('#aiResult').classList.add('show');$('#aiResult').textContent='Menganalisis kebutuhan…';logEvent('recommendation_request',{query:q});try{const r=await fetch('/api/recommend',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:q,products:state.products})});const j=await r.json();$('#aiResult').innerHTML=`<strong>${esc(j.title||'Recommendation')}</strong><br>${esc(j.summary||j.message||'Shortlist siap diproses.')}${(j.recommendations||[]).length?'<br><br>'+j.recommendations.map(x=>`• <b>${esc(x.name)}</b> — ${esc(x.why||'Fit berdasarkan kebutuhan')}`).join('<br>'):''}<br><br><span class="muted">${esc(j.disclosure||'')}`;}catch{const list=state.products.filter(p=>matches(p,q)).slice(0,3);$('#aiResult').innerHTML=list.length?`<strong>Shortlist awal</strong><br>${list.map(p=>`• <b>${esc(p.name)}</b> — ${esc(p.problem_solved)}`).join('<br>')}<br><br><span class="muted">Live AI belum tersedia; memakai local Product Intelligence.</span>`:'<strong>Research signal tercatat.</strong><br><span class="muted">Belum ada kandidat di database untuk kebutuhan ini.</span>'}}
async function boot(){try{const [p,c,g]=await Promise.all([fetch('/data/products.json',{cache:'no-store'}).then(r=>r.json()),fetch('/data/categories.json',{cache:'no-store'}).then(r=>r.json()),fetch('/data/guides.json',{cache:'no-store'}).then(r=>r.json())]);state.products=p.products||[];state.categories=c||[];state.guides=g||[];renderCategories();$('#guideGrid').innerHTML=state.guides.map(x=>`<article class="guide"><div class="tag">${esc(x.tag)}</div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></article>`).join('');renderProducts();updateCompare()}catch{toast('Gagal memuat data. Silakan refresh.')}}
$('#searchBtn').onclick=runSearch;$('#heroSearch').onkeydown=e=>e.key==='Enter'&&runSearch();$('#navSearch').onkeydown=e=>{if(e.key==='Enter'){$('#heroSearch').value=e.target.value;runSearch()}};$('#aiBtn').onclick=aiRecommend;$('#openCompare').onclick=openCompare;$('#clearCompare').onclick=()=>{state.compare=[];updateCompare();renderProducts()};$$('[data-q]').forEach(b=>b.onclick=()=>{$('#heroSearch').value=b.dataset.q;runSearch()});$$('.filter').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));$('#menuBtn').onclick=()=>$('#mobileLinks').classList.toggle('hidden');$$('.overlay').forEach(o=>o.addEventListener('click',e=>e.target===o&&o.classList.add('hidden')));boot();
