const CATS=[['⌂','Home & Living'],['◉','Kitchen & Cooking'],['♙','Baby & Parenting'],['◈','Gadget & Electronics'],['▣','Automotive'],['✦','Beauty & Personal Care'],['▤','Office & Productivity'],['✧','AI & Software'],['＋','Health & Wellness'],['✈','Travel'],['◇','Fashion'],['◌','Food & Grocery'],['◇','Education'],['⚒','Tools & DIY'],['○','Lifestyle'],['↗','Services']];
const state={products:[],guides:[],filter:'all',query:'',compare:[],saved:new Set(JSON.parse(localStorage.getItem('rp_saved')||'[]')),sessionId:crypto.randomUUID?crypto.randomUUID():String(Date.now())};
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2300)}
function track(name,metadata={}){try{const a=JSON.parse(localStorage.getItem('rp_events')||'[]');a.push({event_name:name,session_id:state.sessionId,metadata,occurred_at:new Date().toISOString()});localStorage.setItem('rp_events',JSON.stringify(a.slice(-500)))}catch{}fetch('/api/event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event_name:name,session_id:state.sessionId,metadata})}).catch(()=>{})}
function matches(p,q){if(!q)return true;const alias={rumah:['home','living'],bayi:['baby'],gadget:['electronics'],dapur:['kitchen'],masak:['cooking','kitchen'],mobil:['automotive'],motor:['automotive'],kerja:['office','productivity'],software:['ai','software']};const h=[p.name,p.brand,p.category,p.problem_solved,...(p.use_cases||[]),...(p.subcategories||[])].join(' ').toLowerCase();return q.toLowerCase().split(/\s+/).filter(Boolean).every(t=>h.includes(t)||(alias[t]||[]).some(a=>h.includes(a)))}
function filtered(){return state.products.filter(p=>(state.filter==='all'||p.category===state.filter)&&matches(p,state.query))}
function categoryUI(){const e=$('#categoryGrid');e.innerHTML=CATS.map(([i,n])=>`<button data-cat="${esc(n)}"><i>${i}</i><span>${esc(n)}</span></button>`).join('');$$('#categoryGrid [data-cat]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.cat;state.query='';$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===state.filter));render();location.hash='picks';track('category_select',{category:state.filter})})}
function scoreLabel(p){if(p.status==='VERIFIED')return ['Verified','ok'];if(p.status==='PENDING_VERIFICATION')return ['Verification in progress','pending'];return [String(p.status||'Review'), 'pending']}
function card(p){const [label]=scoreLabel(p);const active=p.affiliate?.status==='VERIFIED_ACTIVE';return `<article class="card"><div class="card-visual"><span class="status">${label}</span><div class="mark">✓</div></div><div class="card-body"><div class="micro">${esc(p.brand||'RuangPilih')} · ${esc(p.category||p.entity_type||'Solution')}</div><h3>${esc(p.name)}</h3><p>${esc(p.problem_solved||p.description||'Curated candidate in the RuangPilih intelligence graph.')}</p><div class="pills">${(p.use_cases||[]).slice(0,3).map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div><div class="card-actions"><button class="btn btn-dark" data-action="detail" data-id="${esc(p.product_id)}">Lihat Detail</button><button class="btn" data-action="compare" data-id="${esc(p.product_id)}">${state.compare.includes(p.product_id)?'✓ Compared':'+ Compare'}</button><button class="btn" data-action="save" data-id="${esc(p.product_id)}">${state.saved.has(p.product_id)?'★ Saved':'☆ Save'}</button></div><div class="micro" style="margin-top:10px">${active?'Verified purchase route':'Commerce route pending verification'}</div></div></article>`}
function render(){const list=filtered();$('#productGrid').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><h3>Belum ada kandidat yang memenuhi kebutuhan ini.</h3><p>Permintaan ini menjadi research signal untuk discovery RuangPilih berikutnya.</p></div>`;$$('#productGrid [data-action]').forEach(el=>el.onclick=()=>{const id=el.dataset.id,a=el.dataset.action;a==='detail'&&openProduct(id);a==='compare'&&toggleCompare(id);a==='save'&&toggleSave(id)});$('#picksCount').textContent=list.length}
async function openProduct(id){const p=state.products.find(x=>x.product_id===id);if(!p)return;$('#modalMeta').textContent=`${p.brand||'RuangPilih'} · ${p.category||p.entity_type||'Solution'}`;$('#modalTitle').textContent=p.name;$('#modalProblem').textContent=p.problem_solved||p.description||'';const ev=p.evidence||[];$('#modalBody').innerHTML=`<div class="detail-grid"><div><b>Verification</b><div class="detail-value">${esc(p.status||'PENDING_VERIFICATION')}</div></div><div><b>Freshness</b><div class="detail-value">${esc(p.updated_at||p.last_updated||'Not recorded')}</div></div><div><b>Use cases</b><div class="detail-value">${esc((p.use_cases||[]).join(', ')||'-')}</div></div><div><b>Source</b><div class="detail-value">${ev.length?'Evidence available':'Evidence collection pending'}</div></div></div><div class="evidence">${ev.length?ev.map(e=>`<div><b>${esc(e.fact||'Evidence')}</b>${e.source_url?`<a href="${esc(e.source_url)}" target="_blank" rel="noopener">source</a>`:''}</div>`).join(''):`<div>RuangPilih belum akan menyajikan klaim material sebagai fakta terverifikasi tanpa evidence.</div>`}<div class="disclosure">Affiliate disclosure: RuangPilih may receive a commission from eligible purchase routes. Commercial relationships do not determine the editorial verdict.</div></div>`;const r=await fetch(`/api/route?product_id=${encodeURIComponent(id)}`).then(x=>x.json()).catch(()=>null);$('#modalBuy').href=r?.url&&r.url!=='#'?r.url:(p.affiliate?.route||'#');$('#modalBuy').textContent=r?.marketplace?`Lihat di ${r.marketplace}`:'Lihat Pilihan Beli';$('#modalCompare').onclick=()=>{toggleCompare(id);closeOverlays()};$('#productOverlay').classList.remove('hidden');track('product_view',{product_id:id})}
function closeOverlays(){$$('.overlay').forEach(x=>x.classList.add('hidden'))}
function toggleSave(id){state.saved.has(id)?state.saved.delete(id):state.saved.add(id);localStorage.setItem('rp_saved',JSON.stringify([...state.saved]));render();toast(state.saved.has(id)?'Disimpan di RuangPilih':'Dihapus dari simpanan');track('save_toggle',{product_id:id,saved:state.saved.has(id)})}
function toggleCompare(id){if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else{if(state.compare.length>=4)return toast('Maksimal 4 pilihan.');state.compare.push(id)}$('#compareCount').textContent=state.compare.length;$('#compareBar').classList.toggle('hidden',state.compare.length===0);render();track('compare_toggle',{product_id:id})}
function openCompare(){const ps=state.compare.map(id=>state.products.find(p=>p.product_id===id)).filter(Boolean);$('#compareContent').innerHTML=ps.length?`<div class="compare-wrap"><table class="compare-table"><thead><tr><th>Decision factor</th>${ps.map(p=>`<th>${esc(p.name)}</th>`).join('')}</tr></thead><tbody>${[['Kategori',p=>p.category],['Use case',p=>(p.use_cases||[]).join(', ')],['Verification',p=>p.status],['Problem solved',p=>p.problem_solved]].map(([n,f])=>`<tr><td>${esc(n)}</td>${ps.map(p=>`<td>${esc(f(p)||'-')}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="note">Recommendation economics never override material user fit or trust signals.</p>`:'<p>Belum ada pilihan untuk dibandingkan.</p>';$('#compareOverlay').classList.remove('hidden');track('compare_open',{count:ps.length})}
function search(q){state.query=q.trim();state.filter='all';$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));render();if(state.query){location.hash='picks';$('#picks').scrollIntoView({behavior:'smooth'});}track('search',{query:state.query,results:filtered().length})}
async function aiRecommend(){const q=$('#aiInput').value.trim();if(!q)return toast('Ceritakan kebutuhanmu dulu.');$('#aiResult').classList.add('show');$('#aiResult').textContent='Menganalisis kebutuhan…';track('recommendation_request',{query:q});try{const r=await fetch('/api/recommend',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:q})});const j=await r.json();$('#aiResult').innerHTML=`<b>${esc(j.title||'Shortlist')}</b><br>${esc(j.summary||'')}</br>${(j.recommendations||[]).map(x=>`<div class="ai-pick"><strong>${esc(x.name)}</strong><span>${esc(x.why||'')}</span></div>`).join('')}<small>${esc(j.disclosure||'')}</small>`}catch{const ls=state.products.filter(p=>matches(p,q)).slice(0,3);$('#aiResult').innerHTML=ls.length?`<b>Shortlist awal</b>${ls.map(p=>`<div class="ai-pick"><strong>${esc(p.name)}</strong><span>${esc(p.problem_solved||'Candidate')}</span></div>`).join('')}<small>Gemini tidak tersedia; local intelligence fallback digunakan.</small>`:'<b>Belum ada kandidat.</b><small>Query dicatat sebagai research signal.</small>'}}
async function boot(){try{const r=await fetch('/api/catalog',{cache:'no-store'});const j=await r.json();state.products=j.products||[];const g=await fetch('/data/guides.json',{cache:'no-store'}).then(x=>x.json()).catch(()=>[]);state.guides=g||[];categoryUI();$('#guideGrid').innerHTML=state.guides.map(g=>`<article class="guide"><div class="tag">${esc(g.tag||'Guide')}</div><h3>${esc(g.title)}</h3><p>${esc(g.description)}</p></article>`).join('');render()}catch(e){console.error(e);toast('Data RuangPilih belum dapat dimuat. Refresh untuk mencoba lagi.')}}
$('#heroForm').addEventListener('submit',e=>{e.preventDefault();search($('#heroSearch').value)});$('#searchForm').addEventListener('submit',e=>{e.preventDefault();search($('#searchInput').value);closeOverlays()});$('#openSearch').onclick=()=>$('#searchOverlay').classList.remove('hidden');$('#menuBtn').onclick=()=>$('#mobileNav').classList.toggle('hidden');$('#aiBtn').onclick=aiRecommend;$('#openCompare').onclick=openCompare;$('#clearCompare').onclick=()=>{state.compare=[];$('#compareBar').classList.add('hidden');render()};$$('[data-query]').forEach(b=>b.onclick=()=>{$('#heroSearch').value=b.dataset.query;search(b.dataset.query)});$$('.filter').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===state.filter));render();track('filter',{filter:state.filter})});$$('[data-close]').forEach(b=>b.onclick=closeOverlays);$$('.overlay').forEach(o=>o.addEventListener('click',e=>e.target===o&&o.classList.add('hidden')));boot();