import fs from 'node:fs';
import assert from 'node:assert/strict';

const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const html=read('index.html');
const app=read('app.js');
const css=read('style.css');
const pkg=JSON.parse(read('package.json'));
const cats=JSON.parse(read('data/categories.json'));
const guides=JSON.parse(read('data/guides.json'));
const products=JSON.parse(read('data/products.json'));

assert.match(html,/Helping You Choose with Confidence/);
assert.match(html,/RuangPilih/);
assert.match(html,/AI Decision Assistant/);
assert.match(html,/Smart Picks/);
assert.match(html,/id="categoryGrid"/);
assert.match(html,/id="productGrid"/);
assert.match(html,/id="guideGrid"/);
assert.match(html,/id="openCompare"/);
assert.match(html,/id="heroForm"/);
assert.match(html,/id="searchForm"/);
assert.match(html,/id="aiBtn"/);
assert.match(html,/id="productOverlay"/);
assert.doesNotMatch(html,/premium-mockup\.css/);
assert.match(app,/api\/catalog/);
assert.match(app,/api\/recommend/);
assert.match(app,/api\/route/);
assert.match(app,/categoryUI/);
assert.doesNotMatch(app,/openComparePreview/);
assert.match(css,/--gold/);
assert.match(css,/hero-shell|hero-main|hero/);
assert.match(css,/prefers-reduced-motion/);
assert.ok(pkg.dependencies['@neondatabase/serverless']);
assert.ok(cats.length>=10);
assert.ok(guides.length>=3);
assert.ok(products.products?.length>=1);
console.log('RuangPilih production smoke tests passed');
